run:
  timeout: 3m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - gocyclo
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: checkstyle
      path: .report/lint.xml
  print-issued-lines: true
  print-linter-name: true
